### ISSUE TITLE
cluster and user name conflict on add kubeconfig with same context cluster and user

### ISSUE THREAD

**Issue by poneding** [sunny0826/kubecm#1047]
**Describe the bug**
If the cluster and user names of multiple KubeConfig contexts are duplicated, the final merged kubeconfig will have the wrong content!

**To Reproduce**
1. Prepare three kubeconfig files, such as `.kube/cluster1`,`kube/cluster2`,`kube/cluster3`
2. They have same context:

```yaml
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
```

3. use kubecm merge them:

```bash
touch ~/.kube/config
kubecm add --file .kube/cluster1
kubecm rename # cluster1
kubecm add --file .kube/cluster2
kubecm rename # cluster2
kubecm add --file .kube/cluster3
```

4. Result: .kube/cluster3 add done, but context

<img width="1418" alt="image" src="https://github.com/user-attachments/assets/02708bd3-5440-467d-ad48-525a0a335931" />
