### ISSUE TITLE
Error: no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by cig0** [sunny0826/kubecm#17]
Hi,

I got this error message when trying to list the namespaces of my GKE cluster; please find below a sanitised version of `~/.kube/config`:

```
% cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: blah
    server: https://localhost:6443
  name: default
- cluster:
    certificate-authority-data: blah
    server: https://1.2.3.4
  name: gke_cluster
contexts:
- context:
    cluster: gke_cluster
    namespace: default
    user: gke_cluster
  name: gke_cluster
- context:
    cluster: default
    user: default
  name: minikube
current-context: gke_cluster
kind: Config
preferences: {}
users:
- name: default
  user:
    password: blah
    username: blah
- name: gke_cluster
  user:
    auth-provider:
      config:
        access-token: token_blah
        cmd-args: config config-helper --format=json
        cmd-path: /Users/cig0/Applications/google-cloud-sdk/bin/gcloud
        expiry: "blah"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

It is worth noting that I'm able to work with this context/cluster using `kubectl` or other CLI tools.

% kubecm version
Version: 0.13.0
GoOs: darwin
GoArch: amd64

Thanks! 🙏
