### ISSUE TITLE
kubecm uses wrong user and cluster name

### ISSUE THREAD

**Issue by SnGmng** [sunny0826/kubecm#351]
kube cm adds the cluster with wrong cluster name and wrong user name: 

![image](https://user-images.githubusercontent.com/38666407/170089634-332ed36b-280d-40b3-b437-3ea01d80abce.png)

kubecm uses the wrong names `cluster-95ct8cddbt` and `user-95ct8cddbt` instead of the correct names `k3d-testkube` and `admin@k3d-testkube`

Here is original kubeconfig:
```yaml
---
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: REDACTED
    name: k3d-testkube
contexts:
  - context:
      cluster: k3d-testkube
      user: admin@k3d-testkube
    name: k3d-testkube
current-context: k3d-testkube
kind: Config
preferences: {}
users:
  - name: admin@k3d-testkube
    user:
      client-certificate-data: REDACTED
      client-key-data: REDACTED
```

Here is after `kubecm add -f`:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: REDACTED
  name: cluster-95ct8cddbt # wrong
contexts:
- context:
    cluster: cluster-95ct8cddbt # wrong
    user: user-95ct8cddbt # wrong
  name: k3d-testkube
current-context: ""
kind: Config
preferences: {}
users:
- name: user-95ct8cddbt # wrong
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```
