### ISSUE TITLE
Generate context and user name smartly when merging config

### ISSUE THREAD

**Issue by yujunz** [sunny0826/kubecm#768]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when merging config produces random context names, e.g.

```
Loading KubeConfig file: /Users/yujunz/.kube/config
Add Context: config-ktd65k9dkh
Add Context: config-9bbc58ghm5
Add Context: config-7864ft646m
Add Context: config-4hd4hd7cd7
Add Context: config-k6hh45mbt5
Add Context: config-mg6mch5976
Add Context: config-6kf6g9mbc4
```
and duplicated users
```
name: vault-user
  user:
    client-certificate: client.crt
    client-key: client
- name: vault-user-7864ft646m
  user:
    client-certificate: client.crt
    client-key: client
- name: vault-user-k6hh45mbt5
  user:
    client-certificate: client.crt
    client-key: client
```
**Describe the solution you'd like**
Format the context from cluster and user name, e.g. user@cluster or simply cluster when there is no ambiguity.

**Describe alternatives you've considered**
Allow user to define the format string

**Additional context**
N/A
